language: java
os: linux
dist: bionic
group: edge
git:
  depth: false
env:
  global:
  # for updates check (dl.google.com/android/repository/repository2-1.xml)
  - ANDROID_SDK_CMD_TOOLS=commandlinetools-linux-5842447_latest.zip
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache/

before_install:
  # download and unzip Android SDK command line tools
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_CMD_TOOLS
  - mkdir -p $HOME/sdk/cmdline-tools && unzip -q $ANDROID_SDK_CMD_TOOLS -d $HOME/sdk/cmdline-tools
  # set SDK tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/cmdline-tools/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
install:
  # accept licenses for all available packages that have not already been accepted
  - yes | sdkmanager --licenses >/dev/null
before_script:
  # set executable flag for gradle wrapper
  - chmod +x gradlew
  # create dir for gradle settings
  - mkdir -p $HOME/.gradle
  # disable gradle daemon for current user
  - echo "org.gradle.daemon=false" >> $HOME/.gradle/gradle.properties
  # set gradle log format to plain
  - echo "org.gradle.console=plain" >> $HOME/.gradle/gradle.properties
  # enable gradle build cache
  - echo "org.gradle.caching=true" >> $HOME/.gradle/gradle.properties
  # log all gradle warnings
  - echo "org.gradle.warning.mode=all" >> $HOME/.gradle/gradle.properties
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
  - rm -f  $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
  - rm -f  $HOME/.gradle/caches/*/executionHistory/executionHistory.lock
  - rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
  - rm -f  $HOME/.gradle/caches/journal-1/journal-1.lock
  - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
  - rm -f  $HOME/.gradle/caches/user-id.txt.lock
  # only cache latest gradle version used by the wrapper
  # list content in wrapper/dist sorted by modification time and remove entries starting by the second entry
  - ls -d $HOME/.gradle/wrapper/dists/* -1t | tail -n +2 | xargs rm -rf

jobs:
  include:
  - # Build debug
    if: branch IN (develop, master)
    script: "./gradlew assembleDebug --scan"
  - # Build and deploy release on tags
    if: tag IS present
    script: "./gradlew assembleRelease --scan"
    deploy:
      provider: releases
      api_key:
        secure: "EGnLEVpEeWXg4hWIhNgOPi+FaCLj7tdsxmrjYaU3bpVnccMmIvF4mpNhrefrAUMOSM3CoCOe6bjVhFExxFifposcn9fgHvk5GqUV1XRXcLTr7lfjtT/fdSat9GY80V7tfQBa9F6pf/tt/wCIKUF11QiSs3xiQ4f3JftnuNibDp+9b8Th8BHP1gUcQZhhD0hQ87OuGz5Hk69A09J8PSNFhUND66ENIBSLBLvi4WTNwTjgwKmaxkJNNhl+b+WPDI6jw7sMAeGYv9AddoqpEQ3H14akD07ZjnVsU4tyTZI4SHDOqCjVwZosnMvRL1fuTdwG+SjWJEWc0hEUHavYMAPQqU8HVrMe7J87qAI2Tl4PVhc/YFEyER/yKezZYopz3l77MNnlDnX8KT1utnuDCn72Vk4xIkZEeKpkhZ6+bIDP7v7PeJtyycmE5ajZ1w4cdJXVc4F3bpdTQWSMZISoGmsCdjipxiZ+mRdkQrIFTRuXP5QLzga5VD2fXCVnR6wCk3QC/eYoUcK2vHGMmwSbvoPSMCX56LxGqPPm9E7Jb+IWR/fFfA6fxofWdE+x/Q7rE9WRiusuh3kySujivl2n39HM1KHyjvsC1avixNofirTo4NAqhQsKGc24L3/Fo4DL0embSdCxCOG0Za8W5dwSiUt2ahUA5CUH49VzSruzf2I/j94="
      file_glob: true
      file:
        - $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/*.apk
        - $TRAVIS_BUILD_DIR/app/build/outputs/mapping/release/mapping.txt
      skip_cleanup: true
      draft: false
      on:
        tags: true
      name: $TRAVIS_TAG
      tag_name: $TRAVIS_TAG
      body: "Generated release from Travis CI for build $TRAVIS_BUILD_NUMBER"